// <auto-generated />
using System;
using FirstApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329103215_AddWeeklyPlan")]
    partial class AddWeeklyPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FirstApp.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/exercises/Photos/foto1.jpg",
                            Name = "Bench Press",
                            Notes = "Chest",
                            VideoUrl = "/exercises/Videos/Video1.mp4"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/exercises/Photos/foto2.jpg",
                            Name = "Skull Crusher",
                            Notes = "Triceps",
                            VideoUrl = "/exercises/Videos/Video1.mp4"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/exercises/Photos/foto3.jpg",
                            Name = "Pull Up",
                            Notes = "Back",
                            VideoUrl = "/exercises/Videos/Video1.mp4"
                        });
                });

            modelBuilder.Entity("FirstApp.Api.Models.WeeklyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("FirstApp.Api.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FirstApp.Api.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("FirstApp.Api.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float>("WeightKg")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId", "SetIndex")
                        .IsUnique();

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("FirstApp.Api.Models.WeeklyPlan", b =>
                {
                    b.OwnsOne("FirstApp.Api.Models.Week", "Week", b1 =>
                        {
                            b1.Property<int>("WeeklyPlanId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("FridayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("MondayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("SaturdayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("SundayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("ThursdayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TuesdayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("WednesdayWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("WeeklyPlanId");

                            b1.HasIndex("FridayWorkoutId");

                            b1.HasIndex("MondayWorkoutId");

                            b1.HasIndex("SaturdayWorkoutId");

                            b1.HasIndex("SundayWorkoutId");

                            b1.HasIndex("ThursdayWorkoutId");

                            b1.HasIndex("TuesdayWorkoutId");

                            b1.HasIndex("WednesdayWorkoutId");

                            b1.ToTable("WeeklyPlans");

                            b1.HasOne("FirstApp.Api.Models.Workout", "Friday")
                                .WithMany()
                                .HasForeignKey("FridayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.HasOne("FirstApp.Api.Models.Workout", "Monday")
                                .WithMany()
                                .HasForeignKey("MondayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.HasOne("FirstApp.Api.Models.Workout", "Saturday")
                                .WithMany()
                                .HasForeignKey("SaturdayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.HasOne("FirstApp.Api.Models.Workout", "Sunday")
                                .WithMany()
                                .HasForeignKey("SundayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.HasOne("FirstApp.Api.Models.Workout", "Thursday")
                                .WithMany()
                                .HasForeignKey("ThursdayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.HasOne("FirstApp.Api.Models.Workout", "Tuesday")
                                .WithMany()
                                .HasForeignKey("TuesdayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.HasOne("FirstApp.Api.Models.Workout", "Wednesday")
                                .WithMany()
                                .HasForeignKey("WednesdayWorkoutId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.WithOwner()
                                .HasForeignKey("WeeklyPlanId");

                            b1.Navigation("Friday");

                            b1.Navigation("Monday");

                            b1.Navigation("Saturday");

                            b1.Navigation("Sunday");

                            b1.Navigation("Thursday");

                            b1.Navigation("Tuesday");

                            b1.Navigation("Wednesday");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("FirstApp.Api.Models.WorkoutExercise", b =>
                {
                    b.HasOne("FirstApp.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirstApp.Api.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FirstApp.Api.Models.WorkoutSet", b =>
                {
                    b.HasOne("FirstApp.Api.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("FirstApp.Api.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FirstApp.Api.Models.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
