// <auto-generated />
using FirstApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FirstApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425214549_AddDefaultKeyToDefaults")]
    partial class AddDefaultKeyToDefaults
    {
    }
}
